### ISSUE TITLE
Bug: `AttributeError: 'LoggerWithStatusbar' object has no attribute 'showlog'`

### ISSUE THREAD

**Issue by dishb** [lebao3105/texteditor#7]
```
texteditor.backend.get_config 09:34:53 texteditor.backend.get_config ~ Error occured: (open log file) -
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/texteditor/backend/logger.py", line 41, in __init__
    open(self.logfile, mode="w")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dishb/.logs/texteditor.log'

texteditor.extensions.autosave 09:34:53 texteditor.extensions.autosave ~ Error occured: (open log file) -
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/texteditor/backend/logger.py", line 41, in __init__
    open(self.logfile, mode="w")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dishb/.logs/texteditor.log'

07-22-2023 09:34:54 texteditor.backend.logger ~ Error occured: (open log file) -
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/texteditor/backend/logger.py", line 41, in __init__
    open(self.logfile, mode="w")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dishb/.logs/texteditor.log'

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/texteditor/backend/logger.py", line 41, in __init__
    open(self.logfile, mode="w")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dishb/.logs/texteditor.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/texteditor/__main__.py", line 4, in <module>
    start_app()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/texteditor/__init__.py", line 53, in start_app
    root = mainwindow.MainWindow()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/texteditor/mainwindow.py", line 40, in __init__
    self.log = logger.LoggerWithStatusbar(self.text_editor.statusbar, showlog=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/texteditor/backend/logger.py", line 213, in __init__
    super().__init__(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/texteditor/backend/logger.py", line 44, in __init__
    self.throwerr(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/texteditor/backend/logger.py", line 222, in throwerr
    if self.showlog is True:
       ^^^^^^^^^^^^
AttributeError: 'LoggerWithStatusbar' object has no attribute 'showlog'
```
After installing with `pip3 install -i https://test.pypi.org/simple/ texteditor`, running with `python3 -m texteditor`, with the following specs:
- pip 23.2.1
- Python 3.11.4
- macOS 12.6.7

**Comment by lebao3105** [comment]
About `no such file`, create `~/.logs` manualy, and about the missing object, that’s my fault.

**Comment by lebao3105** [comment]
I will take a better look of it tomorrow as it’s late in Vietnam (~0am)

**Comment by dishb** [comment]
In the code you can add the following:
```python
from os.path import exists, expanduser

path = expanduser("~/.logs")

if not exists(path):
    with open(path, "x", encoding = "utf-8") as file:
        file.close()
```

**Comment by lebao3105** [comment]
But wait you have `~/.config/texteditor` created? I don’t see any related error about it

**Comment by dishb** [comment]
Yep I have `~/.config/texteditor/configs.ini`

**Comment by lebao3105** [comment]
Thanks, but it’s fixed in 1.5

**Comment by dishb** [comment]
Ah okay, I'm using code from the `main` branch. I'll switch to wip/1.5 in the future.

**Comment by lebao3105** [comment]
> Ah okay, I'm using code from the `main` branch. I'll switch to wip/1.5 in the future.

It’s a bit…broken. (1.5 alpha)
